compatibility_date = "2022-02-26"

name = "feedback"
type = "javascript"

workers_dev = false

routes = ["feedback.jocolina.com/*"]

main = "./index.js"

[[kv_namespaces]]
binding = "FEEDBACK_DATABASE"
id = "e7925ec64f7a405cb7f0181b2ea314b1"
